name: pegasus_trasher
description: Pegasus Trasher - Security Lock App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.5.1
  audio_session: ^0.2.2
  permission_handler: ^12.0.1
  window_manager: ^0.5.1
  just_audio: ^0.10.5
  vibration: ^3.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^3.0.2  # HAPUS atau comment baris ini

flutter:
  uses-material-design: true
  
  assets:
    - assets/hacked.mp3
    - assets/fonts/
  
  fonts:
    - family: ShareTechMono
      fonts:
        - asset: assets/fonts/ShareTechMono-Regular.ttf
