name: pegasus_trasher
description: Pegasus Trasher Security App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.3.2
  permission_handler: ^11.3.1
  window_manager: ^0.3.4

flutter:
  uses-material-design: true
  assets:
    - assets/hacked.mp3
  fonts:
    - family: ShareTechMono
      fonts:
        - asset: assets/fonts/ShareTechMono-Regular.ttf
